apiVersion: apps/v1
kind: Deployment
metadata:
  name: liftstats
spec:
  replicas: 1
  selector:
    matchLabels: liftstats
      app: 
  template:
    metadata:
      labels:
        app: liftstats
    spec:
      containers:
        - name: flask-container
          image: liftstats
          imagePullPolicy: Never
          ports:
            - containerPort: 4000