apiVersion: v1
kind: Service
metadata:
  name: liftstats
spec:
  selector:
    app: liftstats
  ports:
    - protocol: TCP
      port: 80 //external browser request
      targetPort: 4000 //Flask inside container
  type: NodePort //opens external TCP port for browsers